// Long-form tutorial bodies, keyed by slug (see ./site.ts for the index metadata).
// Each tutorial renders an intro, a numbered step list, and a closing tip.
//
// Every step screenshot is a REAL, captured screen of the running
// application — never a mockup. They are generated by the pipeline in
// tools/tutorial-screenshots/ against a purpose-built fictional "demo org"
// (Meridian Portfolio Group) and land in /public/tutorials/<persona>/<id>.png.
// See tools/tutorial-screenshots/manifest.ts for the single source of truth
// on which screenshot belongs to which persona, and tools/tutorial-screenshots/README.md
// for how to regenerate them after a UI change.

export interface TutorialStep {
  title: string;
  body: string;
  /** Real captured screenshot for this step, e.g. "/tutorials/admin/dashboard.png" */
  screenshotSrc?: string;
  screenshotAlt?: string;
}

export interface TutorialBody {
  intro: string;
  steps: TutorialStep[];
  tip?: string;
  next?: string; // slug of the recommended next tutorial
}

export const tutorialContent: Record<string, TutorialBody> = {
  'viewer-guide': {
    intro:
      "Every internal teammate — even before any elevated role is assigned — can see this much of the portfolio. It's read-only, but it's a genuinely useful home base: dashboards, exports, calendars, and the residential side of the business.",
    steps: [
      {
        title: 'Read the analytics dashboard',
        body: 'Open the portfolio analytics workspace for KPIs and trends across every office and lease — SLA compliance, cost per square foot, and backlog, all in one view.',
        screenshotSrc: '/tutorials/viewer/analytics.png',
        screenshotAlt: 'Portfolio analytics dashboard showing KPIs and trend charts',
      },
      {
        title: 'Export a report',
        body: 'Generate polished, board-ready report exports on demand — no need to ask an admin or editor to pull the numbers for you.',
        screenshotSrc: '/tutorials/viewer/reports.png',
        screenshotAlt: 'Report exports screen with generated report list',
      },
      {
        title: 'Check the lease expiration calendar',
        body: 'See every upcoming lease expiration across the portfolio laid out on a calendar, so nothing sneaks up on the team.',
        screenshotSrc: '/tutorials/viewer/lease-calendar.png',
        screenshotAlt: 'Lease expiration calendar view',
      },
      {
        title: 'Browse residential units',
        body: 'Get a portfolio-wide view of residential units — occupancy, unit details, and status — without needing edit access.',
        screenshotSrc: '/tutorials/viewer/residential-units.png',
        screenshotAlt: 'Residential units overview list',
      },
      {
        title: 'Review vacancy listings',
        body: 'See the marketing pages generated for vacant residential units, exactly as a prospective renter would find them.',
        screenshotSrc: '/tutorials/viewer/vacancy-listings.png',
        screenshotAlt: 'Vacancy listing marketing pages',
      },
      {
        title: 'Read resident announcements',
        body: 'Review announcements sent to residents — building notices, maintenance windows, and community updates.',
        screenshotSrc: '/tutorials/viewer/announcements.png',
        screenshotAlt: 'Resident announcements list',
      },
    ],
    tip: "Viewer is the default role every internal user has — editor, accountant, and admin all build on top of this same read-only foundation, they just add write access to their own area.",
    next: 'editor-guide',
  },
  'editor-guide': {
    intro:
      'Editors run the day-to-day: leases, maintenance, HVAC, transitions, waivers, and the administration hub. Everything here is also open to admins, but an editor never needs to wait on one.',
    steps: [
      {
        title: 'Work the lease register',
        body: 'Browse every lease in the portfolio, filter by status, and jump into any record for its full detail.',
        screenshotSrc: '/tutorials/editor/leases.png',
        screenshotAlt: 'Lease register table',
      },
      {
        title: 'Open a lease detail page',
        body: 'Review key terms, dates, and attached documents for a single lease, and edit any field directly.',
        screenshotSrc: '/tutorials/editor/lease-detail.png',
        screenshotAlt: 'Lease detail page with key terms',
      },
      {
        title: 'Triage the maintenance ticket queue',
        body: 'See every open work order, its priority, and its SLA countdown, and assign a vendor straight from the list.',
        screenshotSrc: '/tutorials/editor/maintenance-tickets.png',
        screenshotAlt: 'Maintenance ticket queue',
      },
      {
        title: 'Track HVAC contracts',
        body: 'Keep equipment and service contracts organized by office, with renewal dates visible at a glance.',
        screenshotSrc: '/tutorials/editor/hvac.png',
        screenshotAlt: 'HVAC contracts and equipment tracking',
      },
      {
        title: 'Run an office transition checklist',
        body: 'Move an office through a structured transition — move-in, move-out, or ownership handoff — without missing a step.',
        screenshotSrc: '/tutorials/editor/transitions.png',
        screenshotAlt: 'Office transition checklist',
      },
      {
        title: 'Build a digital waiver template',
        body: 'Create a reusable waiver template ready to send for e-signature — liability, photo release, or your own custom form.',
        screenshotSrc: '/tutorials/editor/waivers.png',
        screenshotAlt: 'Digital waiver templates list',
      },
      {
        title: 'Track operating expenses',
        body: 'Log and categorize day-to-day operating expenses against the right office, ready for the accounting team to reconcile.',
        screenshotSrc: '/tutorials/editor/operating-expenses.png',
        screenshotAlt: 'Operating expense tracking screen',
      },
      {
        title: 'Use the administration hub',
        body: 'The administration area centralizes automation rules, integrations, and system configuration for editors and admins alike.',
        screenshotSrc: '/tutorials/editor/administration.png',
        screenshotAlt: 'Administration hub',
      },
      {
        title: 'Track certificates of insurance',
        body: 'Keep vendor and landlord insurance certificates on file, with expiration and verification status visible at a glance.',
        screenshotSrc: '/tutorials/editor/insurance-certificates.png',
        screenshotAlt: 'Insurance certificate tracking screen',
      },
    ],
    tip: 'Assign a vendor to a ticket and they get their own portal login automatically — see the Vendor Portal guide for what they see on their end.',
    next: 'accountant-guide',
  },
  'accountant-guide': {
    intro:
      'The books live here: general ledger, financial statements, AP/AR, budgeting, and owner/trust accounting for the residential side. Everything in this guide is also open to admins.',
    steps: [
      {
        title: 'Post to the general ledger',
        body: 'Review the chart of accounts and journal entries, and post manual entries when you need to.',
        screenshotSrc: '/tutorials/accountant/general-ledger.png',
        screenshotAlt: 'General ledger and journal entries screen',
      },
      {
        title: 'Read the financial statements',
        body: 'Pull income statements and balance sheets straight from posted GL activity, ready to share.',
        screenshotSrc: '/tutorials/accountant/financial-statements.png',
        screenshotAlt: 'Financial statements screen',
      },
      {
        title: 'Manage accounts payable',
        body: 'Enter vendor bills and record payments — each one posts straight to the general ledger automatically.',
        screenshotSrc: '/tutorials/accountant/accounts-payable.png',
        screenshotAlt: 'Accounts payable: vendor bills and payments',
      },
      {
        title: 'Manage accounts receivable',
        body: 'Track tenant billing and outstanding receivables across the commercial portfolio.',
        screenshotSrc: '/tutorials/accountant/accounts-receivable.png',
        screenshotAlt: 'Accounts receivable: tenant billing screen',
      },
      {
        title: 'Compare budget to actuals',
        body: 'See how spending is tracking against budget for every office, updated as new transactions post.',
        screenshotSrc: '/tutorials/accountant/budgeting.png',
        screenshotAlt: 'Budget vs actuals screen',
      },
      {
        title: 'Handle owner / trust accounting',
        body: 'Manage owner statements and distributions for the residential properties you manage on their behalf.',
        screenshotSrc: '/tutorials/accountant/owners.png',
        screenshotAlt: 'Owner and trust accounting screen',
      },
      {
        title: 'Watch the rent collection dashboard',
        body: 'See rent collected, outstanding, and overdue across every residential unit in one dashboard.',
        screenshotSrc: '/tutorials/accountant/rent-collection.png',
        screenshotAlt: 'Rent collection dashboard',
      },
    ],
    tip: 'Owner statements generated here are exactly what the property owner sees in their own Owner Portal — see that guide for their side of it.',
    next: 'admin-guide',
  },
  'admin-guide': {
    intro:
      "Admin is the top internal tier: everything editors and accountants can do, plus the organization's own settings — team, security, and audit.",
    steps: [
      {
        title: 'Start from the portfolio dashboard',
        body: 'The dashboard hub is what every user lands on after login — a portfolio-wide snapshot of financials, tickets, and lease activity.',
        screenshotSrc: '/tutorials/admin/dashboard.png',
        screenshotAlt: 'Portfolio dashboard hub after login',
      },
      {
        title: 'Set up your offices directory',
        body: 'Create and organize every office in the portfolio — the anchor that leases, tickets, vendors, and HVAC records all attach to.',
        screenshotSrc: '/tutorials/admin/offices.png',
        screenshotAlt: 'Offices directory list',
      },
      {
        title: 'Invite your team and assign roles',
        body: 'Invite teammates by email and assign each one admin, editor, accountant, or viewer — every plan includes unlimited users.',
        screenshotSrc: '/tutorials/admin/users.png',
        screenshotAlt: 'Team members and role management screen',
      },
      {
        title: 'Configure organization site settings',
        body: 'Set your organization-wide preferences and branding from one place.',
        screenshotSrc: '/tutorials/admin/site-settings.png',
        screenshotAlt: 'Organization site settings screen',
      },
      {
        title: 'Issue API keys',
        body: 'Generate scoped API keys for integrations that need to read or write portfolio data programmatically.',
        screenshotSrc: '/tutorials/admin/api-keys.png',
        screenshotAlt: 'API keys management screen',
      },
      {
        title: 'Subscribe to webhooks',
        body: 'Register webhook subscriptions so your own systems get notified the moment something changes in Portfolio Desk.',
        screenshotSrc: '/tutorials/admin/webhooks.png',
        screenshotAlt: 'Webhook subscriptions screen',
      },
      {
        title: 'Review the activity log',
        body: 'Every create, update, and delete across the organization is recorded here — a full, exportable audit trail.',
        screenshotSrc: '/tutorials/admin/activity-log.png',
        screenshotAlt: 'Full audit and activity log',
      },
    ],
    tip: 'Set up one representative office end-to-end before inviting the rest of the team — it makes every other guide in this series click into place faster.',
    next: 'resident-portal-guide',
  },
  'resident-portal-guide': {
    intro:
      "Residents never log into the main app — they get a single emailed invite link that drops them straight into their own self-serve portal. Here's what that looks like from their side.",
    steps: [
      {
        title: 'Send the invite',
        body: "An editor or admin mints a resident portal invite from the resident's record. It arrives as a one-time signup link by email — no separate account setup on your end.",
      },
      {
        title: 'The resident lands on their portal home',
        body: 'After signing up, the resident sees their lease, account balance, maintenance requests, documents, and announcements — and nothing from the rest of your organization.',
        screenshotSrc: '/tutorials/resident/home.png',
        screenshotAlt: 'Resident portal home showing lease, balance, and profile',
      },
    ],
    tip: 'The resident portal is entirely self-serve after the first invite — residents can log back in any time without you re-sending a link.',
    next: 'owner-portal-guide',
  },
  'owner-portal-guide': {
    intro:
      'Property owners you manage for get their own portal for statements and distributions, without ever seeing your internal management tools.',
    steps: [
      {
        title: 'Send the invite',
        body: "An accountant or admin mints an owner portal invite from the owner's record, delivered as a one-time signup link by email.",
      },
      {
        title: 'The owner lands on their portal home',
        body: 'Owners see their own statements and distribution history for the properties they hold — scoped strictly to their own portfolio.',
        screenshotSrc: '/tutorials/owner/home.png',
        screenshotAlt: 'Owner portal home showing statements and distributions',
      },
    ],
    tip: "Owner statements shown here are generated from the same owner/trust accounting your accountants manage — see the Accountant Guide for that side.",
    next: 'vendor-portal-guide',
  },
  'vendor-portal-guide': {
    intro:
      'Vendors and contractors get a lightweight work portal scoped to exactly the tickets assigned to them — no account, no password to manage.',
    steps: [
      {
        title: 'Assign a ticket',
        body: 'An editor assigns a maintenance ticket to a vendor. The vendor is notified by email with a portal link scoped to their assigned work.',
      },
      {
        title: 'The vendor works their portal home',
        body: 'Vendors see their assigned work orders, can update status, complete work, and upload invoices — all from one page.',
        screenshotSrc: '/tutorials/vendor/home.png',
        screenshotAlt: 'Vendor work portal showing assigned work orders',
      },
    ],
    tip: 'Vendor portal access uses a durable token rather than a one-time link, so a vendor can keep coming back to the same portal as new tickets are assigned.',
    next: 'client-portal-guide',
  },
  'client-portal-guide': {
    intro:
      'Commercial landlords and other external clients get a scoped portal showing their property and contact details, without exposing your internal tools.',
    steps: [
      {
        title: 'Send the invite',
        body: 'An admin mints a client portal invite for a landlord or management company contact, delivered as a one-time signup link by email.',
      },
      {
        title: 'The client lands on their portal home',
        body: 'Clients see the property and contact information relevant to them — a clean, scoped view with nothing from the rest of your organization.',
        screenshotSrc: '/tutorials/client/home.png',
        screenshotAlt: 'Client portal home showing property and contact details',
      },
    ],
    tip: 'Client portal invites currently support landlord, management company, resident, and owner contact types.',
    next: 'viewer-guide',
  },
};
